### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by prestwich** [summa-tx/riemann#12]
Commented code examples for:

* building an unsigned tx
* txns with dummy inputs/outputs for sighash_single
* spending a complex p2sh
* turning a script into a p2sh address
* etc.

**Comment by dmorris99** [comment]
Hi @prestwich -- nice library! Please excuse my ignorance, I appreciate this isn't a question specific to the lib, but I'm struggling with Python CLI (on Windows) simply because I've not done any Python dev before.

I've followed the install & test instructions in readme.md - tests run without error (not all, but mostly). **When I try to run a test script directly, e.g.'s below, I get a variety of errors that seem related to dependencies and/or scoping.** No doubt I'm doing it completely wrong.

(Ultimately, I want to shell out to Riemann from a C# console app, to generate tx hex strings including OP_RETURN outputs ("tx hashes"?) that I can sign with Decred RPC wallet server and then broadcast.)

Any pointers much appreciated.

---

C:\SCP\src\riemann>py riemann\tests\test_blake256.py
Traceback (most recent call last):
  File "riemann\tests\test_blake256.py", line 4, in <module>
    from ..blake256 import blake_hash
**ValueError: attempted relative import beyond top-level package**

C:\SCP\src\riemann\riemann>py tests\test_riemann.py
Traceback (most recent call last):
  File "tests\test_riemann.py", line 2, in <module>
    import riemann
**ModuleNotFoundError: No module named 'riemann'**
